# -*- coding: utf-8 -*-
"""Exp - 1  V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-OP0gkY-9bh9tBWfH32To5yxVkY1Im6
"""

#Weather modelling using quadratic equations
a = float(input("Enter the Value of a"))
b = float(input("Enter the Value of b"))
c = float(input("Enter the Value of c"))
x = float(input("Enter the Value of x"))

y = a*(x*x) + b *x + c

print("The value of Y is ",y)
