# -*- coding: utf-8 -*-
"""Exp - 1  V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-OP0gkY-9bh9tBWfH32To5yxVkY1Im6
"""

#Weather modelling using quadratic equations
a = 5
b = 4
c = 2
x = 2

y = a*(x*x) + b *x + c

print("The value of Y is ",y)
